# Sine Wave
# - generic
# - parameters are copied to the inputs at init
[model]
name = "sine"
desc = "Sine wave generator. Generic over input type"

[types.sine.generic.T]
options = ["f32", "f64"]
default = "f64"
[types.sine]
desc = "sine wave generator"
fields = [
    {name="input",  type="sine_params", generic=["T"], tag="in"},
    {name="output", type="T", default=0.0, tag="out"},
    {name="phase",  type="T", default=0.0, tag="data"},
    {name="params", type="sine_params", generic=["T"], tag="params"},
]

[types.sine_params.generic.T]
options = ["f32", "f64"]
default = "f64"
[types.sine_params]
desc = "sine wave parameters"
fields = [
    {name="amplitude", type="T", default=1.0, desc="Maximum amplitude"},
    {name="frequency", type="T", default=1.0, desc="Frequency [Hz]"},
    {name="offset",    type="T", default=0.0, desc="Phase offset"},
    {name="bias",      type="T", default=0.0, desc="Bias offset"},
]
