# Sine Wave
# - generic
# - parameters are copied to the inputs at init
[root]
name = "sine"
desc = "Sine wave generator"

# this model is generic over output signal type

[types.sine]
generic = [{name="T", options=["Float32", "Float64"], default="Float64"}]
desc = "sine wave generator"
fields = [
    {name="input", type="sine_params{T}", tag="in"},
    {name="output", type="T", value=0.0, tag="out"},
    {name="phase", type="T", value=0.0, tag="data"},
    {name="params", type="sine_params{T}", tag="params"},
]

[types.sine_params]
generic = [{name="T", default="Float64"}]
desc = "sine wave parameters"
fields = [
    {name="amplitude", type="T", value=1.0, desc="Maximum amplitude"},
    {name="frequency", type="T", value=1.0, desc="Frequency [Hz]"},
    {name="offset",    type="T", value=0.0, desc="Phase offset"},
]
