# RSIS rust target
rsiswrap = "0.1.0"
desc = "Generate Rust interface for RSIS"

[[template]]
file = "rsis_interface.jl"
filename = "*_interface.rs"
[[template]]
file = "rsis_messagepack.jl"
filename = "*_msgpack.rs"
